[package]
name = "tiny-xlib"
version = "0.1.0"
edition = "2018"

[dependencies]
as-raw-xcb-connection = "1.0.0"
ctor = "0.2.0"
libloading = "0.8.0"

[dev-dependencies]
x11rb = { version = "0.11.1", features = ["allow-unsafe-code"] }
